### ISSUE TITLE
No group notification

### ISSUE THREAD

**Issue by InceptionTime** [roblox-dev-forum/discourse-bulk-messages#2]
It seems when sending a bulk DM to a group, users in that group don't receive a notification

![image](https://user-images.githubusercontent.com/17829184/66337923-01412e00-e938-11e9-94ef-2f9ef316add9.png)

![image](https://user-images.githubusercontent.com/17829184/66337965-0dc58680-e938-11e9-9378-305dcd5066fa.png)

**Comment by Kampfkarren** [comment]
You want DET members to get a notification for what?

**Comment by InceptionTime** [comment]
The account I was using is in the DevEngagementTeam group but after sending out the message I didn't receive any notification about the message. 

Is this intentional?

**Comment by Kampfkarren** [comment]
I believe so, though the latest version I'm having Thomas test will personally send you a message about the success/failure of the message. If a person replies to the message you should also get a notification.

**Comment by Kampfkarren** [comment]
You might have DET muted?

**Comment by InceptionTime** [comment]
Looks to be working now
