### ISSUE TITLE
Ability to have all users in the same message

### ISSUE THREAD

**Issue by InceptionTime** [roblox-dev-forum/discourse-bulk-messages#3]
The plugin seems to sometimes send two notifications about a PM
![image](https://user-images.githubusercontent.com/17829184/66337778-b4f5ee00-e937-11e9-960c-70a1e96b45cf.png)

**Comment by InceptionTime** [comment]
It appears it's not a duplicate notification, instead, it is sending the message twice:
![image](https://user-images.githubusercontent.com/17829184/66338255-a956f700-e938-11e9-935b-bbc76b67d63f.png)
![image](https://user-images.githubusercontent.com/17829184/66338269-b2e05f00-e938-11e9-98d5-b10dfed25ade.png)

**Comment by InceptionTime** [comment]
This seems to be happening as it isn't including both people in the same message. 
Thinking about it, this may be intentional (Could we have an option to disable this and have both people in the same message?)

**Comment by Kampfkarren** [comment]
We discussed this and we're not totally sure what this is referring to, but coefficients has an explanation for you about this.
