### ISSUE TITLE
Bulk messaging 619 users returns 502 error

### ISSUE THREAD

**Issue by InceptionTime** [roblox-dev-forum/discourse-bulk-messages#6]
I attempted to send out a bulk PM to 619 users and I ended up with a 502 error with a list of users (PM me for list)

![image](https://user-images.githubusercontent.com/17829184/66341978-3d788c80-e940-11e9-9267-91ade6e13236.png)

**Comment by InceptionTime** [comment]
This does not tell me that the messages have been sent out to the rest of the users that didn't error.
Nor did anything come up in my notifications

**Comment by InceptionTime** [comment]
We should also list how many people the message didn't send to and their names

**Comment by Kampfkarren** [comment]
On staging, can you press F12, click "Network", then show the output body of the request that fails? It's a bit hard for me to test since I don't have 619 users.

**Comment by InceptionTime** [comment]
Console: 
![image](https://user-images.githubusercontent.com/17829184/66503276-da613400-eabe-11e9-9f75-056309599233.png)

Network:
![image](https://user-images.githubusercontent.com/17829184/66503329-ee0c9a80-eabe-11e9-8327-a2c6a35ebfb6.png)

**Comment by Kampfkarren** [comment]
What's the response body? Also, is this the latest version? I have a new version that I'm testing out with Thomas that might fix this, I can't reproduce it but I also don't have the architecture of the real dev forums.

**Comment by Kampfkarren** [comment]
Great!
