### ISSUE TITLE
Ability to add everyone to 1 DM

### ISSUE THREAD

**Issue by InceptionTime** [roblox-dev-forum/discourse-bulk-messages#7]
Would it be possible to have a checkbox option to include everyone into the DM instead of having it send separately?

We do want both functions, to be able to individually DM each user and then to add them all into 1 big DM

**Comment by buildthomas** [comment]
Discourse doesn't support having hundreds+ loose users in a DM, gotta do via group. Recommended to avoid DMs with massive amounts of people where we can because this is quite bad for notification spam.
